
services:
  - type: web
    name: whats-up-trading
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app   
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
